databases:
  - name: waste_management_db
    databaseName: waste_management
    user: waste_management_user

services:
  - type: web
    name: smart-waste-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT backend.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: waste_management_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@wastemanagement.com
